spring:
  profiles:
    active:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/moneykeeper?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: sksQndqw2!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
